# FROM elixir:1.10.3

# RUN mix local.hex --force \
#   && mix archive.install --force hex phx_new 1.5.1 \
#   && apt-get update \
#   && curl -sL https://deb.nodesource.com/setup_12.x | bash \
#   && apt-get install -y apt-utils \
#   && apt-get install -y nodejs \
#   && apt-get install -y build-essential \
#   && apt-get install -y inotify-tools \
#   && mix local.rebar --force

# # creating a user for the app
# ARG UID=1000
# RUN useradd -m -u $UID daniel
# USER daniel


# RUN mkdir /home/daniel/app
# WORKDIR /home/daniel/app
# RUN mkdir -p /home/daniel/app/deps; chown -R daniel:daniel /home/daniel/app/deps
# VOLUME ["/home/daniel/app/deps"]

# EXPOSE 4000

# COPY . .

# RUN mix local.hex --force
# RUN mix local.rebar --force
# RUN mix deps.get

# RUN ./home/daniel/app/entrypoint.sh

# # RUN mix ecto.create
# # RUN mix ecto.migrate

# # CMD ["mix", "phx.server"]
# CMD ["/home/daniel/app/entrypoint.sh"]

# Use an official Elixir runtime as a parent image

# FROM bitwalker/alpine-elixir-phoenix:latest
# FROM erlang:23

# # elixir expects utf8.
# ENV ELIXIR_VERSION="v1.10.3" \
# 	LANG=C.UTF-8

# RUN set -xe \
# 	&& ELIXIR_DOWNLOAD_URL="https://github.com/elixir-lang/elixir/archive/${ELIXIR_VERSION}.tar.gz" \
# 	&& ELIXIR_DOWNLOAD_SHA256="f3035fc5fdade35c3592a5fa7c8ee1aadb736f565c46b74b68ed7828b3ee1897" \
# 	&& curl -fSL -o elixir-src.tar.gz $ELIXIR_DOWNLOAD_URL \
# 	&& echo "$ELIXIR_DOWNLOAD_SHA256  elixir-src.tar.gz" | sha256sum -c - \
# 	&& mkdir -p /usr/local/src/elixir \
# 	&& tar -xzC /usr/local/src/elixir --strip-components=1 -f elixir-src.tar.gz \
# 	&& rm elixir-src.tar.gz \
# 	&& cd /usr/local/src/elixir \
# 	&& make install clean
# Base image
FROM elixir:1.10.3
RUN apt-get update && \
  apt-get install -y postgresql-client

# Create app directory and copy the Elixir projects into it
RUN mkdir /app
COPY . /app
WORKDIR /app

# Install hex package manager
RUN mix local.hex --force
RUN mix local.rebar --force

RUN chmod +x /app/entrypoint.sh

# Dependencies
RUN mix deps.get
RUN apt-get install make gcc libc-dev

CMD ["/app/entrypoint.sh"]